var basered='#ff0000',
red=chroma(basered).set('hsl.l', 0.6).hex(),

black="#000",white="#fff",
red_lrr=chroma(red).brighten(3).hex(),red_lr=chroma(red).brighten(2).hex(),red_l=chroma(red).brighten(1).hex(),red_d=chroma(red).darken(1).hex(),red_dr=chroma(red).darken(2).hex(),red_drr=chroma(red).darken(3).hex(),
orange=chroma(red).set('hsl.h',30).hex(),orange_lrr=chroma(orange).brighten(3).hex(),orange_lr=chroma(orange).brighten(2).hex(),orange_l=chroma(orange).brighten(1).hex(),orange_d=chroma(orange).darken(1).hex(),orange_dr=chroma(orange).darken(2).hex(),orange_drr=chroma(orange).darken(3).hex(),
yellow_o=chroma(red).set('hsl.h',60).hex(),yellow=chroma(yellow_o).set('hsl.s',.8).hex(),yellow_lrr=chroma(yellow).brighten(3).hex(),yellow_lr=chroma(yellow).brighten(2).hex(),yellow_l=chroma(yellow).brighten(1).hex(),yellow_d=chroma(yellow).darken(1).hex(),yellow_dr=chroma(yellow).darken(2).hex(),yellow_drr=chroma(yellow).darken(3).hex(),
chartreuse_o=chroma(red).set('hsl.h',90).hex(),chartreuse=chroma(chartreuse_o).set('hsl.s',.8).hex(),chartreuse_lrr=chroma(chartreuse).brighten(1.8).hex(),chartreuse_lr=chroma(chartreuse).brighten(1.2).hex(),chartreuse_l=chroma(chartreuse).brighten(.6).hex(),chartreuse_d=chroma(chartreuse).darken(1).hex(),chartreuse_dr=chroma(chartreuse).darken(2).hex(),chartreuse_drr=chroma(chartreuse).darken(3).hex(),
green_o=chroma(red).set('hsl.h',120).hex(),green=chroma(green_o).set('hsl.s',.8).hex(),green_lrr=chroma(green).brighten(3).hex(),green_lr=chroma(green).brighten(2).hex(),green_l=chroma(green).brighten(1).hex(),green_d=chroma(green).darken(1).hex(),green_dr=chroma(green).darken(2).hex(),green_drr=chroma(green).darken(3).hex(),
aquamarine_o=chroma(red).set('hsl.h',150).hex(),aquamarine=chroma(aquamarine_o).set('hsl.s',.8).hex(),aquamarine_lrr=chroma(aquamarine).brighten(3).hex(),aquamarine_lr=chroma(aquamarine).brighten(2).hex(),aquamarine_l=chroma(aquamarine).brighten(1).hex(),aquamarine_d=chroma(aquamarine).darken(1).hex(),aquamarine_dr=chroma(aquamarine).darken(2).hex(),aquamarine_drr=chroma(aquamarine).darken(3).hex(),
cyan_o=chroma(red).set('hsl.h',180).hex(),cyan=chroma(cyan_o).set('hsl.s',.8).hex(),cyan_lrr=chroma(cyan).brighten(2.5).hex(),cyan_lr=chroma(cyan).brighten(2).hex(),cyan_l=chroma(cyan).brighten(1).hex(),cyan_d=chroma(cyan).darken(1).hex(),cyan_dr=chroma(cyan).darken(2).hex(),cyan_drr=chroma(cyan).darken(3).hex(),
blue=chroma(red).set('hsl.h',210).hex(),blue_lrrr=chroma(blue).brighten(3).hex(),blue_lrr=chroma(blue).brighten(2.6).hex(),blue_lr=chroma(blue).brighten(1.8).hex(),blue_l=chroma(blue).brighten(1).hex(),blue_d=chroma(blue).darken(1).hex(),blue_dr=chroma(blue).darken(1.8).hex(),blue_drr=chroma(blue).darken(2.6).hex(),blue_drrr=chroma(blue).darken(3).hex(),
indigo=chroma(red).set('hsl.h',240).hex(),indigo_lrr=chroma(indigo).brighten(3).hex(),indigo_lr=chroma(indigo).brighten(2).hex(),indigo_l=chroma(indigo).brighten(1).hex(),indigo_d=chroma(indigo).darken(1).hex(),indigo_dr=chroma(indigo).darken(2).hex(),indigo_drr=chroma(indigo).darken(3).hex(),
purple=chroma(red).set('hsl.h',270).hex(),purple_lrr=chroma(purple).brighten(3).hex(),purple_lr=chroma(purple).brighten(2).hex(),purple_l=chroma(purple).brighten(1).hex(),purple_d=chroma(purple).darken(1).hex(),purple_dr=chroma(purple).darken(2).hex(),purple_drr=chroma(purple).darken(3).hex(),
pink=chroma(red).set('hsl.h',300).hex(),pink_lrr=chroma(pink).brighten(3).hex(),pink_lr=chroma(pink).brighten(2).hex(),pink_l=chroma(pink).brighten(1).hex(),pink_d=chroma(pink).darken(1).hex(),pink_dr=chroma(pink).darken(2).hex(),pink_drr=chroma(pink).darken(3).hex(),
violetred=chroma(red).set('hsl.h',330).hex(),violetred_lrr=chroma(violetred).brighten(3).hex(),violetred_lr=chroma(violetred).brighten(2).hex(),violetred_l=chroma(violetred).brighten(1).hex(),violetred_d=chroma(violetred).darken(1).hex(),violetred_dr=chroma(violetred).darken(2).hex(),violetred_drr=chroma(violetred).darken(3).hex(),
gray=chroma(black).set('hsl.l',.6).hex(),gray_lrr=chroma(gray).brighten(1.5).hex(),gray_lr=chroma(gray).brighten(1).hex(),gray_l=chroma(gray).brighten(.5).hex(),gray_d=chroma(gray).darken(.5).hex(),gray_dr=chroma(gray).darken(1).hex(),gray_drr=chroma(gray).darken(1.5).hex();
/*
black="#000",white="#fff",
red=chroma(basered).set('hsl.l',0.6).hex(),red_lrr=chroma(red).brighten(1.5).hex(),red_lr=chroma(red).brighten(1).hex(),red_l=chroma(red).brighten(.5).hex(),red_d=chroma(red).darken(.5).hex(),red_dr=chroma(red).darken(1).hex(),red_drr=chroma(red).darken(1.5).hex(),
orange=chroma(red).set('hsl.h',30).hex(),orange_lrr=chroma(orange).brighten(1.5).hex(),orange_lr=chroma(orange).brighten(1).hex(),orange_l=chroma(orange).brighten(.5).hex(),orange_d=chroma(orange).darken(.5).hex(),orange_dr=chroma(orange).darken(1).hex(),orange_drr=chroma(orange).darken(1.5).hex(),yellow_o=chroma(red).set('hsl.h',60).hex(),
yellow=chroma(yellow_o).set('hsl.s',.8).hex(),yellow_lrr=chroma(yellow).brighten(1.5).hex(),yellow_lr=chroma(yellow).brighten(1).hex(),yellow_l=chroma(yellow).brighten(.5).hex(),yellow_d=chroma(yellow).darken(.5).hex(),yellow_dr=chroma(yellow).darken(1).hex(),yellow_drr=chroma(yellow).darken(1.5).hex(),
chartreuse_o=chroma(red).set('hsl.h',90).hex(),chartreuse=chroma(chartreuse_o).set('hsl.s',.8).hex(),chartreuse_lrr=chroma(chartreuse).brighten(1.5).hex(),chartreuse_lr=chroma(chartreuse).brighten(1).hex(),chartreuse_l=chroma(chartreuse).brighten(.5).hex(),chartreuse_d=chroma(chartreuse).darken(.5).hex(),chartreuse_dr=chroma(chartreuse).darken(1).hex(),chartreuse_drr=chroma(chartreuse).darken(1.5).hex(),
green_o=chroma(red).set('hsl.h',120).hex(),green=chroma(green_o).set('hsl.s',.8).hex(),green_lrr=chroma(green).brighten(1.5).hex(),green_lr=chroma(green).brighten(1).hex(),green_l=chroma(green).brighten(.5).hex(),green_d=chroma(green).darken(.5).hex(),green_dr=chroma(green).darken(1).hex(),green_drr=chroma(green).darken(1.5).hex(),
aquamarine_o=chroma(red).set('hsl.h',150).hex(),aquamarine=chroma(aquamarine_o).set('hsl.s',.8).hex(),aquamarine_lrr=chroma(aquamarine).brighten(1.5).hex(),aquamarine_lr=chroma(aquamarine).brighten(1).hex(),aquamarine_l=chroma(aquamarine).brighten(.5).hex(),aquamarine_d=chroma(aquamarine).darken(.5).hex(),aquamarine_dr=chroma(aquamarine).darken(1).hex(),aquamarine_drr=chroma(aquamarine).darken(1.5).hex(),
cyan_o=chroma(red).set('hsl.h',180).hex(),cyan=chroma(cyan_o).set('hsl.s',.8).hex(),cyan_lrr=chroma(cyan).brighten(1.5).hex(),cyan_lr=chroma(cyan).brighten(1).hex(),cyan_l=chroma(cyan).brighten(.5).hex(),cyan_d=chroma(cyan).darken(.5).hex(),cyan_dr=chroma(cyan).darken(1).hex(),cyan_drr=chroma(cyan).darken(1.5).hex(),
blue=chroma(red).set('hsl.h',210).hex(),blue_lrr=chroma(blue).brighten(1.5).hex(),blue_lr=chroma(blue).brighten(1).hex(),blue_l=chroma(blue).brighten(.5).hex(),blue_d=chroma(blue).darken(.5).hex(),blue_dr=chroma(blue).darken(1).hex(),blue_drr=chroma(blue).darken(1.5).hex(),indigo=chroma(red).set('hsl.h',240).hex(),
indigo_lrr=chroma(indigo).brighten(1.5).hex(),indigo_lr=chroma(indigo).brighten(1).hex(),indigo_l=chroma(indigo).brighten(.5).hex(),indigo_d=chroma(indigo).darken(.5).hex(),indigo_dr=chroma(indigo).darken(1).hex(),indigo_drr=chroma(indigo).darken(1.5).hex(),
purple=chroma(red).set('hsl.h',270).hex(),purple_lrr=chroma(purple).brighten(1.5).hex(),purple_lr=chroma(purple).brighten(1).hex(),purple_l=chroma(purple).brighten(.5).hex(),purple_d=chroma(purple).darken(.5).hex(),purple_dr=chroma(purple).darken(1).hex(),purple_drr=chroma(purple).darken(1.5).hex(),
pink=chroma(red).set('hsl.h',300).hex(),pink_lrr=chroma(pink).brighten(1.5).hex(),pink_lr=chroma(pink).brighten(1).hex(),pink_l=chroma(pink).brighten(.5).hex(),pink_d=chroma(pink).darken(.5).hex(),pink_dr=chroma(pink).darken(1).hex(),pink_drr=chroma(pink).darken(1.5).hex(),
violetred=chroma(red).set('hsl.h',330).hex(),violetred_lrr=chroma(violetred).brighten(1.5).hex(),violetred_lr=chroma(violetred).brighten(1).hex(),violetred_l=chroma(violetred).brighten(.5).hex(),violetred_d=chroma(violetred).darken(.5).hex(),violetred_dr=chroma(violetred).darken(1).hex(),violetred_drr=chroma(violetred).darken(1.5).hex(),
gray=chroma(black).set('hsl.l',.6).hex(),gray_lrr=chroma(gray).brighten(1.5).hex(),gray_lr=chroma(gray).brighten(1).hex(),gray_l=chroma(gray).brighten(.5).hex(),gray_d=chroma(gray).darken(.5).hex(),gray_dr=chroma(gray).darken(1).hex(),gray_drr=chroma(gray).set('hsl.l',.3).hex();

black="#000",white="#fff",
red=chroma(basered).set('hsl.l',0.6).hex(),red_lrr=chroma(red).set('hsl.l',.9).hex(),red_lr=chroma(red).set('hsl.l',.8).hex(),red_l=chroma(red).set('hsl.l',.7).hex(),red_d=chroma(red).set('hsl.l',.5).hex(),red_dr=chroma(red).set('hsl.l',.4).hex(),red_drr=chroma(red).set('hsl.l',.3).hex(),orange=chroma(red).set('hsl.h',30).hex(),
orange_lrr=chroma(orange).set('hsl.l',.9).hex(),orange_lr=chroma(orange).set('hsl.l',.8).hex(),orange_l=chroma(orange).set('hsl.l',.7).hex(),orange_d=chroma(orange).set('hsl.l',.5).hex(),orange_dr=chroma(orange).set('hsl.l',.4).hex(),orange_drr=chroma(orange).set('hsl.l',.3).hex(),
yellow_o=chroma(red).set('hsl.h',60).hex(),yellow=chroma(yellow_o).set('hsl.s',.8).hex(),yellow_lrr=chroma(yellow).set('hsl.l',.9).hex(),yellow_lr=chroma(yellow).set('hsl.l',.8).hex(),yellow_l=chroma(yellow).set('hsl.l',.7).hex(),yellow_d=chroma(yellow).set('hsl.l',.5).hex(),yellow_dr=chroma(yellow).set('hsl.l',.4).hex(),yellow_drr=chroma(yellow).set('hsl.l',.3).hex(),
chartreuse_o=chroma(red).set('hsl.h',90).hex(),chartreuse=chroma(chartreuse_o).set('hsl.s',.8).hex(),chartreuse_lrr=chroma(chartreuse).set('hsl.l',.9).hex(),chartreuse_lr=chroma(chartreuse).set('hsl.l',.8).hex(),chartreuse_l=chroma(chartreuse).set('hsl.l',.7).hex(),chartreuse_d=chroma(chartreuse).set('hsl.l',.5).hex(),chartreuse_dr=chroma(chartreuse).set('hsl.l',.4).hex(),chartreuse_drr=chroma(chartreuse).set('hsl.l',.3).hex(),
green_o=chroma(red).set('hsl.h',120).hex(),green=chroma(green_o).set('hsl.s',.8).hex(),green_lrr=chroma(green).set('hsl.l',.9).hex(),green_lr=chroma(green).set('hsl.l',.8).hex(),green_l=chroma(green).set('hsl.l',.7).hex(),green_d=chroma(green).set('hsl.l',.5).hex(),green_dr=chroma(green).set('hsl.l',.4).hex(),green_drr=chroma(green).set('hsl.l',.3).hex(),
aquamarine_o=chroma(red).set('hsl.h',150).hex(),aquamarine=chroma(aquamarine_o).set('hsl.s',.8).hex(),aquamarine_lrr=chroma(aquamarine).set('hsl.l',.9).hex(),aquamarine_lr=chroma(aquamarine).set('hsl.l',.8).hex(),aquamarine_l=chroma(aquamarine).set('hsl.l',.7).hex(),aquamarine_d=chroma(aquamarine).set('hsl.l',.5).hex(),aquamarine_dr=chroma(aquamarine).set('hsl.l',.4).hex(),aquamarine_drr=chroma(aquamarine).set('hsl.l',.3).hex(),
cyan_o=chroma(red).set('hsl.h',180).hex(),cyan=chroma(cyan_o).set('hsl.s',.8).hex(),cyan_lrr=chroma(cyan).set('hsl.l',.9).hex(),cyan_lr=chroma(cyan).set('hsl.l',.8).hex(),cyan_l=chroma(cyan).set('hsl.l',.7).hex(),cyan_d=chroma(cyan).set('hsl.l',.5).hex(),cyan_dr=chroma(cyan).set('hsl.l',.4).hex(),cyan_drr=chroma(cyan).set('hsl.l',.3).hex(),
blue=chroma(red).set('hsl.h',210).hex(),blue_lrr=chroma(blue).set('hsl.l',.9).hex(),blue_lr=chroma(blue).set('hsl.l',.8).hex(),blue_l=chroma(blue).set('hsl.l',.7).hex(),blue_d=chroma(blue).set('hsl.l',.5).hex(),blue_dr=chroma(blue).set('hsl.l',.4).hex(),blue_drr=chroma(blue).set('hsl.l',.3).hex(),
indigo=chroma(red).set('hsl.h',240).hex(),indigo_lrr=chroma(indigo).set('hsl.l',.9).hex(),indigo_lr=chroma(indigo).set('hsl.l',.8).hex(),indigo_l=chroma(indigo).set('hsl.l',.7).hex(),indigo_d=chroma(indigo).set('hsl.l',.5).hex(),indigo_dr=chroma(indigo).set('hsl.l',.4).hex(),indigo_drr=chroma(indigo).set('hsl.l',.3).hex(),
purple=chroma(red).set('hsl.h',270).hex(),purple_lrr=chroma(purple).set('hsl.l',.9).hex(),purple_lr=chroma(purple).set('hsl.l',.8).hex(),purple_l=chroma(purple).set('hsl.l',.7).hex(),purple_d=chroma(purple).set('hsl.l',.5).hex(),purple_dr=chroma(purple).set('hsl.l',.4).hex(),purple_drr=chroma(purple).set('hsl.l',.3).hex(),
pink=chroma(red).set('hsl.h',300).hex(),pink_lrr=chroma(pink).set('hsl.l',.9).hex(),pink_lr=chroma(pink).set('hsl.l',.8).hex(),pink_l=chroma(pink).set('hsl.l',.7).hex(),pink_d=chroma(pink).set('hsl.l',.5).hex(),pink_dr=chroma(pink).set('hsl.l',.4).hex(),pink_drr=chroma(pink).set('hsl.l',.3).hex(),
violetred=chroma(red).set('hsl.h',330).hex(),violetred_lrr=chroma(violetred).set('hsl.l',.9).hex(),violetred_lr=chroma(violetred).set('hsl.l',.8).hex(),violetred_l=chroma(violetred).set('hsl.l',.7).hex(),violetred_d=chroma(violetred).set('hsl.l',.5).hex(),violetred_dr=chroma(violetred).set('hsl.l',.4).hex(),violetred_drr=chroma(violetred).set('hsl.l',.3).hex(),
gray=chroma(black).set('hsl.l',.6).hex(),gray_lrr=chroma(gray).set('hsl.l',.9).hex(),gray_lr=chroma(gray).set('hsl.l',.8).hex(),gray_l=chroma(gray).set('hsl.l',.7).hex(),gray_d=chroma(gray).set('hsl.l',.5).hex(),gray_dr=chroma(gray).set('hsl.l',.4).hex(),gray_drr=chroma(gray).set('hsl.l',.3).hex();

*/

var tc=chroma(blue).darken(.8).hex(),
    tc_lrr=chroma(tc).brighten(3).hex(),
    tc_lr=chroma(tc).brighten(2).hex(),
    tc_l=chroma(tc).brighten(1).hex(),
    tc_d=chroma(tc).darken(1).hex(),
    tc_dr=chroma(tc).darken(2).hex(),
    tc_drr=chroma(tc).darken(3).hex();



